# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poisson_predictor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="poisson_predictor.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x17poisson_predictor.proto"E\n\x11PairScoresRequest\x12\x17\n\x0f\x61ve_home_scored\x18\x01 \x01(\x02\x12\x17\n\x0f\x61ve_away_scored\x18\x02 \x01(\x02"{\n\x11TeamScoresRequest\x12\x17\n\x0f\x61ve_scored_home\x18\x01 \x01(\x02\x12\x19\n\x11\x61ve_conceded_home\x18\x02 \x01(\x02\x12\x17\n\x0f\x61ve_scored_away\x18\x03 \x01(\x02\x12\x19\n\x11\x61ve_conceded_away\x18\x04 \x01(\x02"n\n\x12PredictionResponse\x12+\n\x04odds\x18\x01 \x03(\x0b\x32\x1d.PredictionResponse.OddsEntry\x1a+\n\tOddsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x9c\x01\n\x10PoissonPredictor\x12\x43\n\x16PredictOnAvePairScores\x12\x12.PairScoresRequest\x1a\x13.PredictionResponse"\x00\x12\x43\n\x16PredictOnAveTeamScores\x12\x12.TeamScoresRequest\x1a\x13.PredictionResponse"\x00\x62\x06proto3',
)


_PAIRSCORESREQUEST = _descriptor.Descriptor(
    name="PairScoresRequest",
    full_name="PairScoresRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ave_home_scored",
            full_name="PairScoresRequest.ave_home_scored",
            index=0,
            number=1,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="ave_away_scored",
            full_name="PairScoresRequest.ave_away_scored",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=27,
    serialized_end=96,
)


_TEAMSCORESREQUEST = _descriptor.Descriptor(
    name="TeamScoresRequest",
    full_name="TeamScoresRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ave_scored_home",
            full_name="TeamScoresRequest.ave_scored_home",
            index=0,
            number=1,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="ave_conceded_home",
            full_name="TeamScoresRequest.ave_conceded_home",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="ave_scored_away",
            full_name="TeamScoresRequest.ave_scored_away",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="ave_conceded_away",
            full_name="TeamScoresRequest.ave_conceded_away",
            index=3,
            number=4,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=98,
    serialized_end=221,
)


_PREDICTIONRESPONSE_ODDSENTRY = _descriptor.Descriptor(
    name="OddsEntry",
    full_name="PredictionResponse.OddsEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="PredictionResponse.OddsEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="PredictionResponse.OddsEntry.value",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=290,
    serialized_end=333,
)

_PREDICTIONRESPONSE = _descriptor.Descriptor(
    name="PredictionResponse",
    full_name="PredictionResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="odds",
            full_name="PredictionResponse.odds",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[_PREDICTIONRESPONSE_ODDSENTRY,],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=223,
    serialized_end=333,
)

_PREDICTIONRESPONSE_ODDSENTRY.containing_type = _PREDICTIONRESPONSE
_PREDICTIONRESPONSE.fields_by_name["odds"].message_type = _PREDICTIONRESPONSE_ODDSENTRY
DESCRIPTOR.message_types_by_name["PairScoresRequest"] = _PAIRSCORESREQUEST
DESCRIPTOR.message_types_by_name["TeamScoresRequest"] = _TEAMSCORESREQUEST
DESCRIPTOR.message_types_by_name["PredictionResponse"] = _PREDICTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PairScoresRequest = _reflection.GeneratedProtocolMessageType(
    "PairScoresRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PAIRSCORESREQUEST,
        "__module__": "poisson_predictor_pb2"
        # @@protoc_insertion_point(class_scope:PairScoresRequest)
    },
)
_sym_db.RegisterMessage(PairScoresRequest)

TeamScoresRequest = _reflection.GeneratedProtocolMessageType(
    "TeamScoresRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _TEAMSCORESREQUEST,
        "__module__": "poisson_predictor_pb2"
        # @@protoc_insertion_point(class_scope:TeamScoresRequest)
    },
)
_sym_db.RegisterMessage(TeamScoresRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType(
    "PredictionResponse",
    (_message.Message,),
    {
        "OddsEntry": _reflection.GeneratedProtocolMessageType(
            "OddsEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _PREDICTIONRESPONSE_ODDSENTRY,
                "__module__": "poisson_predictor_pb2"
                # @@protoc_insertion_point(class_scope:PredictionResponse.OddsEntry)
            },
        ),
        "DESCRIPTOR": _PREDICTIONRESPONSE,
        "__module__": "poisson_predictor_pb2"
        # @@protoc_insertion_point(class_scope:PredictionResponse)
    },
)
_sym_db.RegisterMessage(PredictionResponse)
_sym_db.RegisterMessage(PredictionResponse.OddsEntry)


_PREDICTIONRESPONSE_ODDSENTRY._options = None

_POISSONPREDICTOR = _descriptor.ServiceDescriptor(
    name="PoissonPredictor",
    full_name="PoissonPredictor",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=336,
    serialized_end=492,
    methods=[
        _descriptor.MethodDescriptor(
            name="PredictOnAvePairScores",
            full_name="PoissonPredictor.PredictOnAvePairScores",
            index=0,
            containing_service=None,
            input_type=_PAIRSCORESREQUEST,
            output_type=_PREDICTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="PredictOnAveTeamScores",
            full_name="PoissonPredictor.PredictOnAveTeamScores",
            index=1,
            containing_service=None,
            input_type=_TEAMSCORESREQUEST,
            output_type=_PREDICTIONRESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_POISSONPREDICTOR)

DESCRIPTOR.services_by_name["PoissonPredictor"] = _POISSONPREDICTOR

# @@protoc_insertion_point(module_scope)
