# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import poisson_predictor_pb2 as poisson__predictor__pb2


class PoissonPredictorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictOnAvePairScores = channel.unary_unary(
                '/PoissonPredictor/PredictOnAvePairScores',
                request_serializer=poisson__predictor__pb2.PairScoresRequest.SerializeToString,
                response_deserializer=poisson__predictor__pb2.PredictionResponse.FromString,
                )
        self.PredictOnAveTeamScores = channel.unary_unary(
                '/PoissonPredictor/PredictOnAveTeamScores',
                request_serializer=poisson__predictor__pb2.TeamScoresRequest.SerializeToString,
                response_deserializer=poisson__predictor__pb2.PredictionResponse.FromString,
                )


class PoissonPredictorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def PredictOnAvePairScores(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictOnAveTeamScores(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoissonPredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictOnAvePairScores': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictOnAvePairScores,
                    request_deserializer=poisson__predictor__pb2.PairScoresRequest.FromString,
                    response_serializer=poisson__predictor__pb2.PredictionResponse.SerializeToString,
            ),
            'PredictOnAveTeamScores': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictOnAveTeamScores,
                    request_deserializer=poisson__predictor__pb2.TeamScoresRequest.FromString,
                    response_serializer=poisson__predictor__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PoissonPredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PoissonPredictor(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def PredictOnAvePairScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PoissonPredictor/PredictOnAvePairScores',
            poisson__predictor__pb2.PairScoresRequest.SerializeToString,
            poisson__predictor__pb2.PredictionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictOnAveTeamScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PoissonPredictor/PredictOnAveTeamScores',
            poisson__predictor__pb2.TeamScoresRequest.SerializeToString,
            poisson__predictor__pb2.PredictionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
